# Alembic配置文件

[alembic]
# 迁移脚本目录
script_location = alembic

# 用于版本控制存储的文件
file_template = %%(year)d%%(month).2d%%(day).2d_%%(hour).2d%%(minute).2d_%%(rev)s_%%(slug)s

# sys.path路径，将从迁移脚本目录导入
prepend_sys_path = .

# 时区偏移
# timezone =

# 最大记录的修订号长度
# truncate_slug_length = 40

# 设置为'true'以运行环境 during
# '离线'迁移
# sourceless = false

# 版本路径分隔符; 默认为 os.pathsep
# version_path_separator = os

# 要使用的输出编码
# output_encoding = utf-8

# sqlalchemy.url
sqlalchemy.url = mysql+pymysql://python:123456@127.0.0.1:3306/py_demo

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatters]
keys = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S